{
  "id": "GHSA-6978-4w92-428p",
  "summary": "Backdoor in api-res-py",
  "details": "api-res-py package in PyPI 0.1 is vulnerable to a code execution backdoor in the request package.",
  "aliases": [
    "CVE-2022-31313"
  ],
  "modified": "2023-03-07T05:47:43.961217Z",
  "published": "2022-06-09T00:00:16Z",
  "database_specific": {
    "cwe_ids": [],
    "severity": "CRITICAL",
    "github_reviewed": true,
    "github_reviewed_at": "2022-06-17T21:51:19Z",
    "nvd_published_at": "2022-06-08T20:15:00Z"
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2022-31313"
    },
    {
      "type": "WEB",
      "url": "https://github.com/rakeshrkz7/as_api_res/issues/1"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/rakeshrkz7/as_api_res"
    },
    {
      "type": "WEB",
      "url": "https://pypi.org/project/api-res-py/"
    },
    {
      "type": "WEB",
      "url": "http://pypi.doubanio.com/simple/request"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "api-res-py",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/api-res-py"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "0.1"
            }
          ]
        }
      ],
      "versions": [
        "0.1"
      ],
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/06/GHSA-6978-4w92-428p/GHSA-6978-4w92-428p.json"
      }
    }
  ],
  "schema_version": "1.3.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  ]
}