{
  "id": "GHSA-2x54-j4m3-r6wx",
  "summary": "High severity vulnerability that affects sqla-yaml-fixtures",
  "details": "Sqla_yaml_fixtures 0.9.1 allows local users to execute arbitrary python code via the fixture_text argument in sqla_yaml_fixtures.load.",
  "aliases": [
    "CVE-2019-3575"
  ],
  "modified": "2023-02-16T23:04:18.678217Z",
  "published": "2019-01-04T17:44:48Z",
  "database_specific": {
    "cwe_ids": [
      "CWE-94"
    ],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2020-06-16T20:53:16Z",
    "nvd_published_at": null
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2019-3575"
    },
    {
      "type": "WEB",
      "url": "https://github.com/schettino72/sqla_yaml_fixtures/issues/20"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-2x54-j4m3-r6wx"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/schettino72/sqla_yaml_fixtures"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "sqla-yaml-fixtures",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/sqla-yaml-fixtures"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "last_affected": "0.9.1"
            }
          ]
        }
      ],
      "versions": [
        "0.1.0",
        "0.1.1",
        "0.1.2",
        "0.2.0",
        "0.3.0",
        "0.4.0",
        "0.5.0",
        "0.6.0",
        "0.7.0",
        "0.8.0",
        "0.9.0",
        "0.9.1"
      ],
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2019/01/GHSA-2x54-j4m3-r6wx/GHSA-2x54-j4m3-r6wx.json"
      }
    }
  ],
  "schema_version": "1.3.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
    }
  ]
}