{
  "id": "GHSA-hw4g-fhcp-x5mq",
  "summary": "Concurrent Execution using Shared Resource with Improper Synchronization in pyftpdlib",
  "details": "Race condition in the FTPHandler class in ftpserver.py in pyftpdlib before 0.5.2 allows remote attackers to cause a denial of service (daemon outage) by establishing and then immediately closing a TCP connection, leading to the accept function having an unexpected value of None for the address, or an ECONNABORTED, EAGAIN, or EWOULDBLOCK error, a related issue to CVE-2010-3492.",
  "aliases": [
    "CVE-2010-3494"
  ],
  "modified": "2023-03-08T05:46:36.181660Z",
  "published": "2022-05-17T05:47:39Z",
  "database_specific": {
    "cwe_ids": [
      "CWE-362"
    ],
    "severity": "MODERATE",
    "github_reviewed": true,
    "github_reviewed_at": "2022-07-08T18:48:45Z",
    "nvd_published_at": "2010-10-19T20:00:00Z"
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2010-3494"
    },
    {
      "type": "WEB",
      "url": "https://bugs.launchpad.net/zodb/+bug/135108"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-hw4g-fhcp-x5mq"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pypa/advisory-database/tree/main/vulns/pyftpdlib/PYSEC-2010-11.yaml"
    },
    {
      "type": "WEB",
      "url": "http://bugs.python.org/issue6706"
    },
    {
      "type": "WEB",
      "url": "http://code.google.com/p/pyftpdlib/issues/detail?id=104"
    },
    {
      "type": "WEB",
      "url": "http://code.google.com/p/pyftpdlib/issues/detail?id=105"
    },
    {
      "type": "WEB",
      "url": "http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY"
    },
    {
      "type": "WEB",
      "url": "http://code.google.com/p/pyftpdlib/source/detail?r=556"
    },
    {
      "type": "WEB",
      "url": "http://code.google.com/p/pyftpdlib/source/diff?spec=svn556&r=556&format=side&path=/trunk/pyftpdlib/ftpserver.py"
    },
    {
      "type": "WEB",
      "url": "http://www.openwall.com/lists/oss-security/2010/09/09/6"
    },
    {
      "type": "WEB",
      "url": "http://www.openwall.com/lists/oss-security/2010/09/11/2"
    },
    {
      "type": "WEB",
      "url": "http://www.openwall.com/lists/oss-security/2010/09/22/3"
    },
    {
      "type": "WEB",
      "url": "http://www.openwall.com/lists/oss-security/2010/09/24/3"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "pyftpdlib",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/pyftpdlib"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.5.2"
            }
          ]
        }
      ],
      "versions": [
        "0.2.0",
        "0.3.0",
        "0.4.0",
        "0.5.0",
        "0.5.1"
      ],
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2022/05/GHSA-hw4g-fhcp-x5mq/GHSA-hw4g-fhcp-x5mq.json"
      }
    }
  ],
  "schema_version": "1.3.0"
}