{
  "id": "GHSA-j7c4-2xj8-wm7r",
  "summary": "Improper Input Validation in kdcproxy",
  "details": "python-kdcproxy before 0.3.2 allows remote attackers to cause a denial of service via a large POST request.",
  "aliases": [
    "CVE-2015-5159"
  ],
  "modified": "2023-02-16T23:32:06.762404Z",
  "published": "2018-11-01T14:49:30Z",
  "database_specific": {
    "cwe_ids": [
      "CWE-20"
    ],
    "severity": "HIGH",
    "github_reviewed": true,
    "github_reviewed_at": "2020-06-16T21:42:25Z",
    "nvd_published_at": null
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2015-5159"
    },
    {
      "type": "WEB",
      "url": "https://github.com/latchset/kdcproxy/commit/f274aa6787cb8b3ec1cc12c440a56665b7231882"
    },
    {
      "type": "WEB",
      "url": "https://bugzilla.redhat.com/show_bug.cgi?id=1245200"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-j7c4-2xj8-wm7r"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/latchset/kdcproxy"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "kdcproxy",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/kdcproxy"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.3.2"
            }
          ]
        }
      ],
      "versions": [
        "0.3.1"
      ],
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2018/11/GHSA-j7c4-2xj8-wm7r/GHSA-j7c4-2xj8-wm7r.json"
      }
    }
  ],
  "schema_version": "1.3.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  ]
}