{
  "id": "GHSA-qppg-v75c-r5ff",
  "summary": "S3Scanner before 2.0.2 allows Directory Traversal",
  "details": "S3Scanner before 2.0.2 allows Directory Traversal via a crafted bucket, as demonstrated by a <Key>../ substring in a ListBucketResult element.",
  "aliases": [
    "CVE-2021-32061"
  ],
  "modified": "2023-02-16T23:30:01.120673Z",
  "published": "2021-11-30T22:21:36Z",
  "database_specific": {
    "cwe_ids": [
      "CWE-22"
    ],
    "severity": "MODERATE",
    "github_reviewed": true,
    "github_reviewed_at": "2021-11-30T16:20:13Z",
    "nvd_published_at": "2021-11-29T03:15:00Z"
  },
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2021-32061"
    },
    {
      "type": "WEB",
      "url": "https://github.com/sa7mon/S3Scanner/issues/122"
    },
    {
      "type": "PACKAGE",
      "url": "https://github.com/sa7mon/S3Scanner/"
    },
    {
      "type": "WEB",
      "url": "https://github.com/sa7mon/S3Scanner/releases/tag/2.0.2"
    },
    {
      "type": "WEB",
      "url": "https://vuln.ryotak.me/advisories/62"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "s3scanner",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/s3scanner"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.0.2"
            }
          ]
        }
      ],
      "versions": [
        "2.0.0",
        "2.0.1"
      ],
      "database_specific": {
        "source": "https://github.com/github/advisory-database/blob/main/advisories/github-reviewed/2021/11/GHSA-qppg-v75c-r5ff/GHSA-qppg-v75c-r5ff.json"
      }
    }
  ],
  "schema_version": "1.3.0",
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:L/A:N"
    }
  ]
}