{
  "id": "PYSEC-2021-423",
  "details": "An issue in Gate One 1.2.0 allows attackers to bypass to the verification check done by the origins list and connect to Gate One instances used by hosts not on the origins list.",
  "aliases": [
    "CVE-2020-19003",
    "GHSA-q6j2-g8qf-wvf7"
  ],
  "modified": "2021-11-16T03:58:44.124463Z",
  "published": "2021-10-06T13:15:00Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://github.com/liftoff/GateOne/issues/728"
    },
    {
      "type": "ADVISORY",
      "url": "https://github.com/advisories/GHSA-q6j2-g8qf-wvf7"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "gateone",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/gateone"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            }
          ]
        }
      ],
      "versions": [
        "1.2.0"
      ],
      "database_specific": {
        "source": "https://github.com/pypa/advisory-database/blob/main/vulns/gateone/PYSEC-2021-423.yaml"
      }
    }
  ],
  "schema_version": "1.3.0"
}