{
  "id": "PYSEC-2022-220",
  "details": "** Reserved ** The pyesasky for python, as distributed on PyPI, included a code-execution backdoor inserted by a third party. The current version, without this backdoor, is 1.2.0-1.4.2.",
  "aliases": [
    "CVE-2022-30885"
  ],
  "modified": "2022-07-06T18:41:16.470294Z",
  "published": "2022-06-24T21:15:00Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://github.com/esdc-esac-esa-int/pyesasky/issues/39"
    },
    {
      "type": "WEB",
      "url": "http://pypi.doubanio.com/simple/request"
    },
    {
      "type": "PACKAGE",
      "url": "https://pypi.org/project/pyesasky/"
    }
  ],
  "affected": [
    {
      "package": {
        "name": "pyesasky",
        "ecosystem": "PyPI",
        "purl": "pkg:pypi/pyesasky"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "1.2.0"
            },
            {
              "fixed": "1.4.3"
            }
          ]
        }
      ],
      "versions": [
        "1.2.0",
        "1.2.1",
        "1.2.11",
        "1.2.2",
        "1.2.4",
        "1.2.5",
        "1.2.6",
        "1.2.7",
        "1.3.0",
        "1.3.1",
        "1.3.2",
        "1.3.3",
        "1.3.4",
        "1.3.5",
        "1.4.0",
        "1.4.1",
        "1.4.1b0",
        "1.4.2"
      ],
      "database_specific": {
        "source": "https://github.com/pypa/advisory-database/blob/main/vulns/pyesasky/PYSEC-2022-220.yaml"
      }
    }
  ],
  "schema_version": "1.3.0"
}