{"resultsPerPage": 1, "startIndex": 0, "totalResults": 1, "format": "NVD_CVE", "version": "2.0", "timestamp": "2023-06-15T21:24:40.530", "vulnerabilities": [{"cve": {"id": "CVE-2021-3533", "sourceIdentifier": "secalert@redhat.com", "published": "2021-06-09T12:15:08.457", "lastModified": "2022-04-25T17:24:37.990", "vulnStatus": "Analyzed", "descriptions": [{"lang": "en", "value": "A flaw was found in Ansible if an ansible user sets ANSIBLE_ASYNC_DIR to a subdirectory of a world writable directory. When this occurs, there is a race condition on the managed machine. A malicious, non-privileged account on the remote machine can exploit the race condition to access the async result data. This flaw affects Ansible Tower 3.7 and Ansible Automation Platform 1.2."}, {"lang": "es", "value": "Se encontr\u00f3 un fallo en Ansible si un usuario ansible ajusta la funci\u00f3n ANSIBLE_ASYNC_DIR en un subdirectorio de un directorio world writable.&#xa0;Cuando esto ocurre, se presenta una condici\u00f3n de carrera en la m\u00e1quina administrada.&#xa0;Una cuenta maliciosa y no privilegiada en la m\u00e1quina remota puede explotar la condici\u00f3n de carrera para acceder a los datos de resultados asincr\u00f3nicos.&#xa0;Este fallo afecta a Ansible Tower versi\u00f3n 3.7 y Ansible Automation Platform versi\u00f3n 1.2"}], "metrics": {"cvssMetricV31": [{"source": "nvd@nist.gov", "type": "Primary", "cvssData": {"version": "3.1", "vectorString": "CVSS:3.1/AV:L/AC:H/PR:L/UI:N/S:U/C:L/I:N/A:N", "attackVector": "LOCAL", "attackComplexity": "HIGH", "privilegesRequired": "LOW", "userInteraction": "NONE", "scope": "UNCHANGED", "confidentialityImpact": "LOW", "integrityImpact": "NONE", "availabilityImpact": "NONE", "baseScore": 2.5, "baseSeverity": "LOW"}, "exploitabilityScore": 1.0, "impactScore": 1.4}], "cvssMetricV2": [{"source": "nvd@nist.gov", "type": "Primary", "cvssData": {"version": "2.0", "vectorString": "AV:L/AC:H/Au:N/C:P/I:N/A:N", "accessVector": "LOCAL", "accessComplexity": "HIGH", "authentication": "NONE", "confidentialityImpact": "PARTIAL", "integrityImpact": "NONE", "availabilityImpact": "NONE", "baseScore": 1.2}, "baseSeverity": "LOW", "exploitabilityScore": 1.9, "impactScore": 2.9, "acInsufInfo": false, "obtainAllPrivilege": false, "obtainUserPrivilege": false, "obtainOtherPrivilege": false, "userInteractionRequired": false}]}, "weaknesses": [{"source": "nvd@nist.gov", "type": "Primary", "description": [{"lang": "en", "value": "CWE-362"}]}, {"source": "secalert@redhat.com", "type": "Secondary", "description": [{"lang": "en", "value": "CWE-367"}]}], "configurations": [{"nodes": [{"operator": "OR", "negate": false, "cpeMatch": [{"vulnerable": true, "criteria": "cpe:2.3:a:redhat:ansible_automation_platform:1.2:*:*:*:*:*:*:*", "matchCriteriaId": "CBA4F8F3-6FC3-4ADD-BB96-A707E94AB0AB"}, {"vulnerable": true, "criteria": "cpe:2.3:a:redhat:ansible_tower:3.7.0:*:*:*:*:*:*:*", "matchCriteriaId": "A5B078C1-9DC2-409E-9845-ED4F041A23DC"}]}]}, {"nodes": [{"operator": "OR", "negate": false, "cpeMatch": [{"vulnerable": true, "criteria": "cpe:2.3:a:redhat:ansible_engine:2.0:*:*:*:*:*:*:*", "matchCriteriaId": "8989CD03-49A1-4831-BF98-9F21592788BE"}, {"vulnerable": true, "criteria": "cpe:2.3:a:redhat:ansible_tower:3.0:*:*:*:*:*:*:*", "matchCriteriaId": "B31C575C-06D2-4CAF-A5B7-B9469B3ED55F"}, {"vulnerable": true, "criteria": "cpe:2.3:o:redhat:enterprise_linux:7.0:*:*:*:*:*:*:*", "matchCriteriaId": "142AD0DD-4CF3-4D74-9442-459CE3347E3A"}]}]}, {"nodes": [{"operator": "OR", "negate": false, "cpeMatch": [{"vulnerable": true, "criteria": "cpe:2.3:o:fedoraproject:fedora:34:*:*:*:*:*:*:*", "matchCriteriaId": "A930E247-0B43-43CB-98FF-6CE7B8189835"}]}]}, {"nodes": [{"operator": "OR", "negate": false, "cpeMatch": [{"vulnerable": true, "criteria": "cpe:2.3:a:redhat:openstack-rdo:-:*:*:*:*:*:*:*", "matchCriteriaId": "DF58FF78-3DD3-4AEF-896A-22F6206312C6"}]}]}], "references": [{"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1956477", "source": "secalert@redhat.com", "tags": ["Issue Tracking", "Vendor Advisory"]}]}}]}